package at.luuk.lolapiwrapper.main;

import at.luuk.lolapiwrapper.entity.Summoner;
import at.luuk.lolapiwrapper.LeagueAPI;

public class LeagueAPIHowTo {

	public static void main(String[] args) {
		// d9595a32-dc5e-441a-838f-82a763b1286d

		// Retrieve a LeagueAPI object with your api key for a specific server
		LeagueAPI api = new LeagueAPI("d9595a32-dc5e-441a-838f-82a763b1286d", "euw");

		// Request a summoner object generated by the Java LoL API Wrapper with
		// a given ingame name
		Summoner summoner = api.getSummoner("luuksen");

		// Print out some stuff
		if (summoner != null) {
			System.out.println(summoner.getName());
			System.out.println(summoner.getSummonerLevel());
			System.out.println(summoner.getRevisionDateStr());
		}
	}

}